site_name: Draworld ElecTRADE Docs
site_description: Documentation for the Draworld-ElecTRADE-APP (PyPSA-based)
repo_url: https://github.com/Shawn-Zhang122/Pypsa-Draworld-ElecTRADE/tree/main
docs_dir: docsrc
site_dir: site, tba.

theme:
  name: material

nav:
  - Home: index.md
  - User Guide:
      - Model Structure: user-guide/model-structure.md
      - Data Pipeline: user-guide/data-pipeline.md
      - Market Clearing: user-guide/clearing.md
      - Outputs & Schema: user-guide/outputs.md
  - Examples:
      - Daily Run: examples/daily-run.md